JUnit Report Action added

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,16 +23,29 @@ jobs:
       - name: Set up Docker Compose
         run: docker-compose up -d
 
-      - name: Test
-        run: docker-compose exec -T app sh -c "python manage.py test"
-
-      - name: Coverage
-        run: docker-compose exec -T app sh -c "pytest --cov=server tests/*"
-
       - name: Lint
         run: | 
           docker-compose exec -T app sh -c "flake8 --ignore=E501,E231 *.py && pylint --disable=C0301 --disable=C0415 *.py"
         continue-on-error: true
+
+#      - name: Test
+#        run: docker-compose exec -T app sh -c "python manage.py test"
+
+      - name: Test with pytest
+        run: |
+          docker-compose exec -T app sh -c "python -m pytest --verbose --junit-xml=junit.xml"
+          - name: Publish Test Report
+            uses: mikepenz/action-junit-report@v3
+            if: success() || failure() # always run even if the previous step fails
+            with:
+              report_paths: '**/junit-reports/TEST-*.xml'
+              detailed_summary: true
+              include_passed: true
+
+      - name: Coverage
+        run: docker-compose exec -T app sh -c "pytest --cov=server tests/*"
+
+
 
       - name: Show logs
         run: docker-compose logs
