JUnit Report Action added

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,19 +28,16 @@ jobs:
           docker-compose exec -T app sh -c "flake8 --ignore=E501,E231 *.py && pylint --disable=C0301 --disable=C0415 *.py"
         continue-on-error: true
 
-#      - name: Test
-#        run: docker-compose exec -T app sh -c "python manage.py test"
+      - name: Run Test
+        run: docker-compose run app sh -c "python -m pytest --verbose --junit-xml=junit.xml"
 
-      - name: Test with pytest
-        run: |
-          docker-compose run app sh -c "python -m pytest --verbose --junit-xml=junit.xml"
-          - name: Publish Test Report
-            uses: mikepenz/action-junit-report@v3
-            if: success() || failure() # always run even if the previous step fails
-            with:
-              report_paths: '**/junit.xml'
-              detailed_summary: true
-              include_passed: true
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/junit.xml'
+          detailed_summary: true
+          include_passed: true
 
       - name: Coverage
         run: docker-compose exec -T app sh -c "pytest --cov=server tests/*"
